@startuml ast_statements

package ast {
    interface Stmt {
        # stmtNode()
    }

    class AssignStmt implements Stmt {
        + Lhs []Expr
        + TokPos token.Pos
        + Tok token.Token
        + Rhs []Expr
    }

    class RangeStmt implements Stmt {
        + For token.Pos
        + Init Stmt
        + Key Expr
        + Value Expr
        + TokPos token.Pos
        + Tok token.Token // ASSIGN, DEFINE
        + X Expr
        + Body *BlockStmt
    }

    class GeneralStmt as "..." implements Stmt
    note bottom of GeneralStmt
        Otros statements,
        pero que no son de importancia
        para la herramienta.
    end note
}

@enduml
